/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AreasWeCoverRouteImport } from './routes/areas-we-cover'
import { Route as CompanyLetRouteImport } from './routes/company-let'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GuaranteedRentRouteImport } from './routes/guaranteed-rent'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeCoverRoute = AreasWeCoverRouteImport.update({
  id: '/areas-we-cover',
  path: '/areas-we-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyLetRoute = CompanyLetRouteImport.update({
  id: '/company-let',
  path: '/company-let',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteedRentRoute = GuaranteedRentRouteImport.update({
  id: '/guaranteed-rent',
  path: '/guaranteed-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-we-cover': typeof AreasWeCoverRoute
  '/company-let': typeof CompanyLetRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/guaranteed-rent': typeof GuaranteedRentRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-we-cover': typeof AreasWeCoverRoute
  '/company-let': typeof CompanyLetRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/guaranteed-rent': typeof GuaranteedRentRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-we-cover': typeof AreasWeCoverRoute
  '/company-let': typeof CompanyLetRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/guaranteed-rent': typeof GuaranteedRentRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/areas-we-cover'
    | '/company-let'
    | '/contact'
    | '/faqs'
    | '/guaranteed-rent'
    | '/services'
    | '/why-choose-us'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/areas-we-cover'
    | '/company-let'
    | '/contact'
    | '/faqs'
    | '/guaranteed-rent'
    | '/services'
    | '/why-choose-us'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/areas-we-cover'
    | '/company-let'
    | '/contact'
    | '/faqs'
    | '/guaranteed-rent'
    | '/services'
    | '/why-choose-us'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasWeCoverRoute: typeof AreasWeCoverRoute
  CompanyLetRoute: typeof CompanyLetRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GuaranteedRentRoute: typeof GuaranteedRentRoute
  ServicesRoute: typeof ServicesRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-cover': {
      id: '/areas-we-cover'
      path: '/areas-we-cover'
      fullPath: '/areas-we-cover'
      preLoaderRoute: typeof AreasWeCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-let': {
      id: '/company-let'
      path: '/company-let'
      fullPath: '/company-let'
      preLoaderRoute: typeof CompanyLetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guaranteed-rent': {
      id: '/guaranteed-rent'
      path: '/guaranteed-rent'
      fullPath: '/guaranteed-rent'
      preLoaderRoute: typeof GuaranteedRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasWeCoverRoute: AreasWeCoverRoute,
  CompanyLetRoute: CompanyLetRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GuaranteedRentRoute: GuaranteedRentRoute,
  ServicesRoute: ServicesRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
